### ISSUE TITLE
TypeError: object is not a function

### ISSUE THREAD

**Issue by holgersindbaek** [linitix/nzero-push#19]
I keep getting this error:

    2015-02-25T04:21:11.141672+00:00 app[worker.1]: var zeroPush = new ZeroPush("iosdev_ZCERp6nYpjd1c4EMZ5h6");
    2015-02-25T04:21:11.141706+00:00 app[worker.1]:                ^
    2015-02-25T04:21:11.154720+00:00 app[worker.1]: TypeError: object is not a function
    2015-02-25T04:21:11.154725+00:00 app[worker.1]:     at Object.<anonymous> (/app/worker.js:5:16)
    2015-02-25T04:21:11.154727+00:00 app[worker.1]:     at Module._compile (module.js:456:26)
    2015-02-25T04:21:11.154728+00:00 app[worker.1]:     at Object.Module._extensions..js (module.js:474:10)
    2015-02-25T04:21:11.154730+00:00 app[worker.1]:     at Module.load (module.js:356:32)
    2015-02-25T04:21:11.154731+00:00 app[worker.1]:     at Function.Module._load (module.js:312:12)
    2015-02-25T04:21:11.154733+00:00 app[worker.1]:     at Function.Module.runMain (module.js:497:10)
    2015-02-25T04:21:11.154735+00:00 app[worker.1]:     at startup (node.js:119:16)
    2015-02-25T04:21:11.154736+00:00 app[worker.1]:     at node.js:929:3
    2015-02-25T04:21:11.141399+00:00 app[worker.1]: /app/worker.js:5
    2015-02-25T04:21:12.017630+00:00 heroku[worker.1]: Process exited with status 8
    2015-02-25T04:21:12.021512+00:00 heroku[worker.1]: State changed from up to crashed

I try to do one of the push examples from the wiki, but can't get past making a zeropush variable:

    var ZeroPush = require("nzero-push");
    var zeroPush = new ZeroPush("iosdev_ZCERp6nYpjd1c4EMZ5h6");

What am I doing wrong here?

**Comment by holgersindbaek** [comment]
No suggestions?

**Comment by snatchev** [comment]
@holgersindbaek I'm not the author of this lib, but I do work for ZeroPush.
By the way nzero-push exports its initializer, it looks like you will need to do something like:

```javascript
var push = require("nzero-push");
var zeropush = new push.ZeroPush("auth-token");
```
or perhaps:

```javascript
var zeropush = new require("nzero-push").ZeroPush("auth-token");
```

Hope that helps.

**Comment by holgersindbaek** [comment]
@snatchev Oh... I'll try it out.

Really like zeropush btw! I've Urban Airship before and it's ok, but feels like you've really taken it to the next level :-). Keep up the good work.

**Comment by igorissen** [comment]
@holgersindbaek I have removed the index file that exports the library. Now you can use your previous code :

```javascript
var ZeroPush = require("nzero-push");
var zeroPush = new ZeroPush("iosdev_ZCERp6nYpjd1c4EMZ5h6");
```

You can install the new version (v1.3.0), try it and close this issue if it is good for you.
